services:
  memcached:
    image: memcached:1.6-alpine
    container_name: ${CONTAINER_NAME}
    ports:
      - "${PANEL_APP_PORT}:11211"
    networks:
      - 1panel-network
    restart: unless-stopped

networks:
  1panel-network:
    external: true
