services:
  rustfs:
    image: rustfs/rustfs:latest
    container_name: ${CONTAINER_NAME}
    environment:
      RUSTFS_ACCESS_KEY: ${RUSTFS_ACCESS_KEY}
      RUSTFS_SECRET_KEY: ${RUSTFS_SECRET_KEY}
      RUSTFS_ADDRESS: "0.0.0.0:9000"
    ports:
      - "${PANEL_APP_PORT}:9000"
    volumes:
      - ./data:/data
    networks:
      - 1panel-network
    restart: unless-stopped

networks:
  1panel-network:
    external: true
