/* eslint-disable */
/* prettier-ignore */
/* oxlint-disable */
/* oxfmt-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const EffectScope: typeof import('vue').EffectScope
  const FILE_ENCODINGS: typeof import('../composables/useTextEncoding').FILE_ENCODINGS
  const acceptHMRUpdate: typeof import('pinia').acceptHMRUpdate
  const aiSceneBody: typeof import('../composables/useAiChat').aiSceneBody
  const b64ToBytes: typeof import('../composables/useTextEncoding').b64ToBytes
  const bytesToB64: typeof import('../composables/useTextEncoding').bytesToB64
  const computed: typeof import('vue').computed
  const createApp: typeof import('vue').createApp
  const createPinia: typeof import('pinia').createPinia
  const customRef: typeof import('vue').customRef
  const decodeWith: typeof import('../composables/useTextEncoding').decodeWith
  const defineAsyncComponent: typeof import('vue').defineAsyncComponent
  const defineComponent: typeof import('vue').defineComponent
  const defineStore: typeof import('pinia').defineStore
  const detectEncoding: typeof import('../composables/useTextEncoding').detectEncoding
  const detectEol: typeof import('../composables/useTextEncoding').detectEol
  const effectScope: typeof import('vue').effectScope
  const encodingLabel: typeof import('../composables/useTextEncoding').encodingLabel
  const getActivePinia: typeof import('pinia').getActivePinia
  const getCurrentInstance: typeof import('vue').getCurrentInstance
  const getCurrentScope: typeof import('vue').getCurrentScope
  const getCurrentWatcher: typeof import('vue').getCurrentWatcher
  const h: typeof import('vue').h
  const inject: typeof import('vue').inject
  const isProxy: typeof import('vue').isProxy
  const isReactive: typeof import('vue').isReactive
  const isReadonly: typeof import('vue').isReadonly
  const isRef: typeof import('vue').isRef
  const isShallow: typeof import('vue').isShallow
  const languageOf: typeof import('../composables/useTextEncoding').languageOf
  const listFileHistory: typeof import('../composables/useFileHistory').listFileHistory
  const mapActions: typeof import('pinia').mapActions
  const mapGetters: typeof import('pinia').mapGetters
  const mapState: typeof import('pinia').mapState
  const mapStores: typeof import('pinia').mapStores
  const mapWritableState: typeof import('pinia').mapWritableState
  const markRaw: typeof import('vue').markRaw
  const nextTick: typeof import('vue').nextTick
  const onActivated: typeof import('vue').onActivated
  const onBeforeMount: typeof import('vue').onBeforeMount
  const onBeforeRouteLeave: typeof import('vue-router').onBeforeRouteLeave
  const onBeforeRouteUpdate: typeof import('vue-router').onBeforeRouteUpdate
  const onBeforeUnmount: typeof import('vue').onBeforeUnmount
  const onBeforeUpdate: typeof import('vue').onBeforeUpdate
  const onDeactivated: typeof import('vue').onDeactivated
  const onErrorCaptured: typeof import('vue').onErrorCaptured
  const onMounted: typeof import('vue').onMounted
  const onRenderTracked: typeof import('vue').onRenderTracked
  const onRenderTriggered: typeof import('vue').onRenderTriggered
  const onScopeDispose: typeof import('vue').onScopeDispose
  const onServerPrefetch: typeof import('vue').onServerPrefetch
  const onUnmounted: typeof import('vue').onUnmounted
  const onUpdated: typeof import('vue').onUpdated
  const onWatcherCleanup: typeof import('vue').onWatcherCleanup
  const provide: typeof import('vue').provide
  const pushFileHistory: typeof import('../composables/useFileHistory').pushFileHistory
  const reactive: typeof import('vue').reactive
  const readonly: typeof import('vue').readonly
  const ref: typeof import('vue').ref
  const resolveComponent: typeof import('vue').resolveComponent
  const setActivePinia: typeof import('pinia').setActivePinia
  const setMapStoreSuffix: typeof import('pinia').setMapStoreSuffix
  const shallowReactive: typeof import('vue').shallowReactive
  const shallowReadonly: typeof import('vue').shallowReadonly
  const shallowRef: typeof import('vue').shallowRef
  const storeToRefs: typeof import('pinia').storeToRefs
  const toRaw: typeof import('vue').toRaw
  const toRef: typeof import('vue').toRef
  const toRefs: typeof import('vue').toRefs
  const toValue: typeof import('vue').toValue
  const triggerRef: typeof import('vue').triggerRef
  const unref: typeof import('vue').unref
  const useAiChat: typeof import('../composables/useAiChat').useAiChat
  const useAppAccountStore: typeof import('../store/modules/app/account').useAppAccountStore
  const useAppAuth: typeof import('../composables/app/auth').useAppAuth
  const useAppKeepAliveStore: typeof import('../store/modules/app/keepAlive').useAppKeepAliveStore
  const useAppMenu: typeof import('../composables/app/menu').useAppMenu
  const useAppMenuStore: typeof import('../store/modules/app/menu').useAppMenuStore
  const useAppPage: typeof import('../composables/app/page').useAppPage
  const useAppRouteStore: typeof import('../store/modules/app/route').useAppRouteStore
  const useAppSettingsStore: typeof import('../store/modules/app/settings').useAppSettingsStore
  const useAppTabbar: typeof import('../composables/app/tabbar').useAppTabbar
  const useAppTabbarStore: typeof import('../store/modules/app/tabbar').useAppTabbarStore
  const useAttrs: typeof import('vue').useAttrs
  const useCssModule: typeof import('vue').useCssModule
  const useCssVars: typeof import('vue').useCssVars
  const useEventBus: typeof import('../composables/useEventBus').useEventBus
  const useFaDrawer: typeof import('@fantastic-admin/components').useFaDrawer
  const useFaImagePreview: typeof import('@fantastic-admin/components').useFaImagePreview
  const useFaModal: typeof import('@fantastic-admin/components').useFaModal
  const useFaToast: typeof import('@fantastic-admin/components').useFaToast
  const useFileEditorStore: typeof import('../store/modules/fileEditor').useFileEditorStore
  const useId: typeof import('vue').useId
  const useLink: typeof import('vue-router').useLink
  const useModel: typeof import('vue').useModel
  const usePagination: typeof import('../composables/usePagination').usePagination
  const usePolling: typeof import('../composables/usePolling').usePolling
  const useReconnectingWs: typeof import('../composables/useReconnectingWs').useReconnectingWs
  const useRoute: typeof import('vue-router').useRoute
  const useRouter: typeof import('vue-router').useRouter
  const useSlots: typeof import('vue').useSlots
  const useTemplateRef: typeof import('vue').useTemplateRef
  const useWorkbenchStore: typeof import('../store/modules/app/workbench').useWorkbenchStore
  const watch: typeof import('vue').watch
  const watchEffect: typeof import('vue').watchEffect
  const watchPostEffect: typeof import('vue').watchPostEffect
  const watchSyncEffect: typeof import('vue').watchSyncEffect
}
// for type re-export
declare global {
  // @ts-ignore
  export type { Component, Slot, Slots, ComponentPublicInstance, ComputedRef, DirectiveBinding, ExtractDefaultPropTypes, ExtractPropTypes, ExtractPublicPropTypes, InjectionKey, PropType, Ref, ShallowRef, MaybeRef, MaybeRefOrGetter, VNode, WritableComputedRef } from 'vue'
  import('vue')
  // @ts-ignore
  export type { WorkbenchApp, WorkbenchWindow } from '../store/modules/app/workbench'
  import('../store/modules/app/workbench')
  // @ts-ignore
  export type { FileEditorTab, FileEditorGroup, FileEditorLayout, FileEditorCursor } from '../store/modules/fileEditor'
  import('../store/modules/fileEditor')
  // @ts-ignore
  export type { AiChatMessage, AiSceneData } from '../composables/useAiChat'
  import('../composables/useAiChat')
  // @ts-ignore
  export type { BusEvent } from '../composables/useEventBus'
  import('../composables/useEventBus')
  // @ts-ignore
  export type { FileHistoryEntry } from '../composables/useFileHistory'
  import('../composables/useFileHistory')
  // @ts-ignore
  export type { PollingOptions } from '../composables/usePolling'
  import('../composables/usePolling')
  // @ts-ignore
  export type { ReconnectingWsOptions } from '../composables/useReconnectingWs'
  import('../composables/useReconnectingWs')
  // @ts-ignore
  export type { FileEncodingOption } from '../composables/useTextEncoding'
  import('../composables/useTextEncoding')
}
