services:
  wp:
    image: wordpress:6.7
    container_name: ${CONTAINER_NAME}
    environment:
      WORDPRESS_DB_HOST: ${CONTAINER_NAME}-db
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wp
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
    ports:
      - "${PANEL_APP_PORT}:80"
    volumes:
      - ./wp:/var/www/html
    depends_on:
      - db
    networks:
      - 1panel-network
    restart: unless-stopped
  db:
    image: mysql:8
    container_name: ${CONTAINER_NAME}-db
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wp
      MYSQL_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${WORDPRESS_DB_PASSWORD}
    volumes:
      - ./db:/var/lib/mysql
    networks:
      - 1panel-network
    restart: unless-stopped

networks:
  1panel-network:
    external: true
