// SshGuardService SSH 安全（M49）：sshd 配置管理（端口/认证开关/root 策略）+ 登录日志 + 暴力破解防护联动。
// 修改走 99-ypanel.conf（Ubuntu Include 优先）+ sshd -t 校验 + reload（不断开现有连接）。
package service

import (
	"context"
	"fmt"
	"path"
	"regexp"
	"sort"
	"strings"

	"github.com/ypanel/core/internal/agentclient"
	"github.com/ypanel/shared/dto"
	"github.com/ypanel/shared/errs"
)

// SshGuardService SSH 安全管理。
type SshGuardService struct {
	nodes *NodeService
}

// NewSshGuardService 创建。
func NewSshGuardService(nodes *NodeService) *SshGuardService {
	return &SshGuardService{nodes: nodes}
}

func (s *SshGuardService) client() (*agentclient.Client, error) {
	node, err := s.nodes.ByID("local")
	if err != nil {
		return nil, err
	}
	return agentclient.New(node.BaseURL, node.Token), nil
}

func (s *SshGuardService) exec(ctx context.Context, cmd string, timeout int) (string, error) {
	ac, err := s.client()
	if err != nil {
		return "", err
	}
	out, err := agentclient.DoJSON[dto.ExecReq, dto.ExecResp](ac, ctx, "POST", "/agent/v1/exec",
		&dto.ExecReq{Command: cmd, TimeoutSecs: timeout})
	if err != nil {
		return "", err
	}
	return out.Output, nil
}

// SshConfig sshd 当前生效配置。
type SshConfig struct {
	Port            int    `json:"port"`
	PasswordAuth    bool   `json:"passwordAuth"`
	PubkeyAuth      bool   `json:"pubkeyAuth"`
	PermitRootLogin string `json:"permitRootLogin"` // yes / no / prohibit-password
}

// GetConfig 从 sshd -T 读取生效配置（含 include 合并结果，准确）。
func (s *SshGuardService) GetConfig(ctx context.Context) (*SshConfig, error) {
	out, err := s.exec(ctx, `sshd -T 2>/dev/null | grep -E '^(port|passwordauthentication|pubkeyauthentication|permitrootlogin) '`, 30)
	if err != nil || strings.TrimSpace(out) == "" {
		return nil, errs.Wrap(errs.ErrBadRequest, "读取 sshd 配置失败（sshd 不可用）")
	}
	cfg := &SshConfig{Port: 22, PasswordAuth: false, PubkeyAuth: true, PermitRootLogin: "prohibit-password"}
	for _, line := range strings.Split(out, "\n") {
		kv := strings.Fields(strings.TrimSpace(line))
		if len(kv) != 2 {
			continue
		}
		switch strings.ToLower(kv[0]) {
		case "port":
			fmt.Sscanf(kv[1], "%d", &cfg.Port)
		case "passwordauthentication":
			cfg.PasswordAuth = kv[1] == "yes"
		case "pubkeyauthentication":
			cfg.PubkeyAuth = kv[1] == "yes"
		case "permitrootlogin":
			cfg.PermitRootLogin = kv[1]
		}
	}
	return cfg, nil
}

var sshValuePattern = regexp.MustCompile(`^(yes|no|prohibit-password)$`)

// SetConfig 修改 sshd 配置（写 /etc/ssh/sshd_config.d/99-ypanel.conf → sshd -t 校验 → reload）。
// 校验失败自动回滚备份。reload 不中断现有 SSH 连接。
func (s *SshGuardService) SetConfig(ctx context.Context, port *int, passwordAuth, pubkeyAuth *bool, permitRootLogin *string) error {
	if port != nil && (*port < 1 || *port > 65535) {
		return errs.Wrap(errs.ErrBadRequest, "SSH 端口需在 1-65535")
	}
	if permitRootLogin != nil && !sshValuePattern.MatchString(*permitRootLogin) {
		return errs.Wrap(errs.ErrBadRequest, "root 登录策略仅允许 yes/no/prohibit-password")
	}
	var lines []string
	if port != nil {
		lines = append(lines, fmt.Sprintf("port %d", *port))
	}
	if passwordAuth != nil {
		v := "no"
		if *passwordAuth {
			v = "yes"
		}
		lines = append(lines, "passwordauthentication "+v)
	}
	if pubkeyAuth != nil {
		v := "yes"
		if *pubkeyAuth {
			v = "no"
		}
		lines = append(lines, "pubkeyauthentication "+v)
	}
	if permitRootLogin != nil {
		lines = append(lines, "permitrootlogin "+*permitRootLogin)
	}
	content := "# generated by YPanel\n" + strings.Join(lines, "\n") + "\n"
	script := fmt.Sprintf(`set -e
mkdir -p /etc/ssh/sshd_config.d
cp /etc/ssh/sshd_config.d/99-ypanel.conf /tmp/yp-ssh.bak 2>/dev/null || true
cat > /etc/ssh/sshd_config.d/99-ypanel.conf << 'YPEOF'
%sYPEOF
if sshd -t 2>/tmp/yp-ssh.err; then
  systemctl reload ssh
  echo SSH_SET_OK
else
  mv /tmp/yp-ssh.bak /etc/ssh/sshd_config.d/99-ypanel.conf 2>/dev/null || rm -f /etc/ssh/sshd_config.d/99-ypanel.conf
  cat /tmp/yp-ssh.err
  exit 1
fi`, content)
	out, err := s.exec(ctx, script, 60)
	if err != nil {
		return err
	}
	if !strings.Contains(out, "SSH_SET_OK") {
		return errs.Wrapc(errs.CodeFileOpFailed, "sshd 校验未通过，已回滚: "+firstLine(tail(out, 300)))
	}
	return nil
}

// SshAttemptEntry SSH 登录失败条目（按 IP 聚合）。
type SshAttemptEntry struct {
	IP     string `json:"ip"`
	Count  int    `json:"count"`
	LastAt string `json:"lastAt"`
	Banned bool   `json:"banned"`
}

// FailedAttempts 解析 sshd 日志中的失败登录（Failed password / Invalid user），按 IP 聚合倒序。
// 数据源：journalctl -t sshd（优先）或 /var/log/auth.log。
func (s *SshGuardService) FailedAttempts(ctx context.Context, limit int) ([]SshAttemptEntry, error) {
	if limit <= 0 || limit > 500 {
		limit = 100
	}
	out, err := s.exec(ctx, `(journalctl -t sshd --since '-7 days' --no-pager 2>/dev/null || cat /var/log/auth.log 2>/dev/null) | grep -E 'Failed password|Invalid user' | tail -2000`, 60)
	if err != nil {
		return []SshAttemptEntry{}, nil
	}
	ipRe := regexp.MustCompile(`(?:from|invalid user \w+ )(\d{1,3}(?:\.\d{1,3}){3})`)
	counts := map[string]int{}
	for _, line := range strings.Split(out, "\n") {
		if m := ipRe.FindStringSubmatch(line); m != nil {
			counts[m[1]]++
		}
	}
	entries := make([]SshAttemptEntry, 0, len(counts))
	for ip, c := range counts {
		entries = append(entries, SshAttemptEntry{IP: ip, Count: c})
	}
	sort.Slice(entries, func(i, j int) bool { return entries[i].Count > entries[j].Count })
	if len(entries) > limit {
		entries = entries[:limit]
	}
	return entries, nil
}

// SshPubKey 公钥条目。
type SshPubKey struct {
	Name        string `json:"name"` // 文件名
	Type        string `json:"type"` // ssh-ed25519 / ssh-rsa
	Fingerprint string `json:"fingerprint"`
	Comment     string `json:"comment"`
}

// ListKeys 列出 root 的 SSH 公钥（名称/类型/指纹/注释）。
func (s *SshGuardService) ListKeys(ctx context.Context) ([]SshPubKey, error) {
	out, err := s.exec(ctx, `for f in /root/.ssh/*.pub; do [ -f "$f" ] && echo "FILE:$f" && ssh-keygen -lf "$f" 2>/dev/null; done`, 30)
	if err != nil {
		return nil, err
	}
	keys := []SshPubKey{}
	cur := ""
	for _, line := range strings.Split(out, "\n") {
		line = strings.TrimSpace(line)
		if strings.HasPrefix(line, "FILE:") {
			cur = path.Base(strings.TrimPrefix(line, "FILE:"))
			continue
		}
		// ssh-keygen -lf: 3072 SHA256:xxxx comment (RSA)
		fields := strings.Fields(line)
		if len(fields) < 3 || cur == "" {
			continue
		}
		fp := fields[1]
		keyType := ""
		comment := strings.Join(fields[2:], " ")
		if len(fields) >= 3 && strings.HasSuffix(fields[len(fields)-1], ")") {
			keyType = strings.Trim(fields[len(fields)-1], "()")
			if len(fields) > 3 {
				comment = strings.Join(fields[2:len(fields)-1], " ")
			}
		}
		keys = append(keys, SshPubKey{Name: cur, Type: keyType, Fingerprint: fp, Comment: comment})
		cur = ""
	}
	return keys, nil
}
