// SshGuardService SSH 安全（M49/M53）：sshd 配置管理（端口/认证开关/root 策略）+ 密钥统一管理 + 登录日志 + 暴力破解防护联动。
// 全部操作按 nodeID 走对应节点 agent 通道（local / 远程同构）。
// 配置修改写 00-ypanel.conf：sshd_config 首值生效（first-value-wins），Include 文件按字典序读取，
// 00- 前缀保证压过 50-cloud-init.conf 等发行版预置文件（99- 前缀曾被抢先生效值静默覆盖，见 M53 计划）。
// 写入后 sshd -t 校验（失败自动回滚）+ reload（不中断现有连接）。
package service

import (
	"context"
	"fmt"
	"path"
	"regexp"
	"sort"
	"strings"
	"sync"
	"time"

	"github.com/ypanel/core/internal/agentclient"
	"github.com/ypanel/shared/dto"
	"github.com/ypanel/shared/errs"
)

// SshGuardService SSH 安全管理。
type SshGuardService struct {
	nodes *NodeService
}

// NewSshGuardService 创建。
func NewSshGuardService(nodes *NodeService) *SshGuardService {
	return &SshGuardService{nodes: nodes}
}

func (s *SshGuardService) client(nodeID string) (*agentclient.Client, error) {
	node, err := s.nodes.ByID(nodeID)
	if err != nil {
		return nil, err
	}
	return agentclient.New(node.BaseURL, node.Token), nil
}

func (s *SshGuardService) exec(ctx context.Context, nodeID, cmd string, timeout int) (string, error) {
	out, _, err := s.execResp(ctx, nodeID, cmd, nil, timeout)
	return out, err
}

// execResp 执行命令并返回输出与退出码；env 注入进程环境（敏感值不进 argv）。
func (s *SshGuardService) execResp(ctx context.Context, nodeID, cmd string, env map[string]string, timeout int) (string, int, error) {
	ac, err := s.client(nodeID)
	if err != nil {
		return "", 0, err
	}
	out, err := agentclient.DoJSON[dto.ExecReq, dto.ExecResp](ac, ctx, "POST", "/agent/v1/exec",
		&dto.ExecReq{Command: cmd, TimeoutSecs: timeout, Env: env})
	if err != nil {
		return "", 0, err
	}
	return out.Output, out.ExitCode, nil
}

// SshConfig sshd 当前生效配置。
type SshConfig struct {
	Port            int    `json:"port"`
	PasswordAuth    bool   `json:"passwordAuth"`
	PubkeyAuth      bool   `json:"pubkeyAuth"`
	PermitRootLogin string `json:"permitRootLogin"` // yes / no / prohibit-password
}

// GetConfig 从 sshd -T 读取生效配置（含 include 合并结果，准确）。
func (s *SshGuardService) GetConfig(ctx context.Context, nodeID string) (*SshConfig, error) {
	out, err := s.exec(ctx, nodeID, `sshd -T 2>/dev/null | grep -E '^(port|passwordauthentication|pubkeyauthentication|permitrootlogin) '`, 30)
	if err != nil || strings.TrimSpace(out) == "" {
		return nil, errs.Wrap(errs.ErrBadRequest, "读取 sshd 配置失败（sshd 不可用）")
	}
	cfg := &SshConfig{Port: 22, PasswordAuth: false, PubkeyAuth: true, PermitRootLogin: "prohibit-password"}
	for _, line := range strings.Split(out, "\n") {
		kv := strings.Fields(strings.TrimSpace(line))
		if len(kv) != 2 {
			continue
		}
		switch strings.ToLower(kv[0]) {
		case "port":
			fmt.Sscanf(kv[1], "%d", &cfg.Port)
		case "passwordauthentication":
			cfg.PasswordAuth = kv[1] == "yes"
		case "pubkeyauthentication":
			cfg.PubkeyAuth = kv[1] == "yes"
		case "permitrootlogin":
			cfg.PermitRootLogin = kv[1]
		}
	}
	return cfg, nil
}

var sshValuePattern = regexp.MustCompile(`^(yes|no|prohibit-password)$`)

// sshdConfFile YPanel 托管的 sshd 配置片段（00- 前缀，首值生效）。
const sshdConfFile = "/etc/ssh/sshd_config.d/00-ypanel.conf"

// SetConfig 修改 sshd 配置（写 00-ypanel.conf → sshd -t 校验 → reload）。
// 校验失败自动回滚备份，并幂等清理旧版 99-ypanel.conf。
// reload 不中断现有 SSH 连接；unit 名按发行版回退（ssh / sshd）。
func (s *SshGuardService) SetConfig(ctx context.Context, nodeID string, port *int, passwordAuth, pubkeyAuth *bool, permitRootLogin *string) error {
	if port != nil && (*port < 1 || *port > 65535) {
		return errs.Wrap(errs.ErrBadRequest, "SSH 端口需在 1-65535")
	}
	if permitRootLogin != nil && !sshValuePattern.MatchString(*permitRootLogin) {
		return errs.Wrap(errs.ErrBadRequest, "root 登录策略仅允许 yes/no/prohibit-password")
	}
	var lines []string
	if port != nil {
		lines = append(lines, fmt.Sprintf("port %d", *port))
	}
	if passwordAuth != nil {
		v := "no"
		if *passwordAuth {
			v = "yes"
		}
		lines = append(lines, "passwordauthentication "+v)
	}
	if pubkeyAuth != nil {
		v := "no"
		if *pubkeyAuth {
			v = "yes"
		}
		lines = append(lines, "pubkeyauthentication "+v)
	}
	if permitRootLogin != nil {
		lines = append(lines, "permitrootlogin "+*permitRootLogin)
	}
	content := "# generated by YPanel\n" + strings.Join(lines, "\n") + "\n"
	script := fmt.Sprintf(`set -e
mkdir -p /etc/ssh/sshd_config.d
cp %s /tmp/yp-ssh.bak 2>/dev/null || true
umask 077
cat > %s << 'YPEOF'
%sYPEOF
rm -f /etc/ssh/sshd_config.d/99-ypanel.conf
if sshd -t 2>/tmp/yp-ssh.err; then
  systemctl reload ssh 2>/dev/null || systemctl reload sshd 2>/dev/null || true
  echo SSH_SET_OK
else
  mv /tmp/yp-ssh.bak %s 2>/dev/null || rm -f %s
  cat /tmp/yp-ssh.err
  exit 1
fi`, sshdConfFile, sshdConfFile, content, sshdConfFile, sshdConfFile)
	out, err := s.exec(ctx, nodeID, script, 60)
	if err != nil {
		return err
	}
	if !strings.Contains(out, "SSH_SET_OK") {
		return errs.Wrapc(errs.CodeFileOpFailed, "sshd 校验未通过，已回滚: "+firstLine(tail(out, 300)))
	}
	return nil
}

// SshAttemptEntry SSH 登录失败条目（按 IP 聚合）。
type SshAttemptEntry struct {
	IP     string `json:"ip"`
	Count  int    `json:"count"`
	LastAt string `json:"lastAt"`
	Banned bool   `json:"banned"`
}

// FailedAttempts 解析 sshd 日志中的失败登录（Failed password / Invalid user），按 IP 聚合倒序。
// 数据源：journalctl -t sshd（优先）或 /var/log/auth.log。
func (s *SshGuardService) FailedAttempts(ctx context.Context, nodeID string, limit int) ([]SshAttemptEntry, error) {
	if limit <= 0 || limit > 500 {
		limit = 100
	}
	out, err := s.exec(ctx, nodeID, `(journalctl -t sshd --since '-7 days' --no-pager 2>/dev/null || cat /var/log/auth.log 2>/dev/null) | grep -E 'Failed password|Invalid user' | tail -2000`, 60)
	if err != nil {
		return []SshAttemptEntry{}, nil
	}
	ipRe := regexp.MustCompile(`(?:from|invalid user \w+ )(\d{1,3}(?:\.\d{1,3}){3})`)
	counts := map[string]int{}
	for _, line := range strings.Split(out, "\n") {
		if m := ipRe.FindStringSubmatch(line); m != nil {
			counts[m[1]]++
		}
	}
	entries := make([]SshAttemptEntry, 0, len(counts))
	for ip, c := range counts {
		entries = append(entries, SshAttemptEntry{IP: ip, Count: c})
	}
	sort.Slice(entries, func(i, j int) bool { return entries[i].Count > entries[j].Count })
	if len(entries) > limit {
		entries = entries[:limit]
	}
	return entries, nil
}

// SshPubKey 公钥条目。
type SshPubKey struct {
	Name        string            `json:"name"` // 文件名（不含 .pub）
	Type        string            `json:"type"` // ssh-ed25519 / ssh-rsa
	Fingerprint string            `json:"fingerprint"`
	Comment     string            `json:"comment"`
	PublicKey   string            `json:"publicKey"` // 公钥单行文本
	DeployedOn  []KeyDeployStatus `json:"deployedOn"`
}

// KeyDeployStatus 密钥在某个节点的分发状态。
type KeyDeployStatus struct {
	NodeID    string `json:"nodeId"`
	NodeName  string `json:"nodeName"`
	Deployed  bool   `json:"deployed"`
	Reachable bool   `json:"reachable"` // 节点是否可达（不可达时状态未知）
}

// ListKeys 列出节点 root 的 SSH 公钥（含公钥内容与全节点分发状态）。
func (s *SshGuardService) ListKeys(ctx context.Context, nodeID string) ([]SshPubKey, error) {
	out, err := s.exec(ctx, nodeID, `for f in /root/.ssh/*.pub; do [ -f "$f" ] && echo "FILE:$f" && cat "$f" && ssh-keygen -lf "$f" 2>/dev/null; done`, 30)
	if err != nil {
		return nil, err
	}
	type rawKey struct{ name, pub, fpLine string }
	raws := []rawKey{}
	cur := rawKey{}
	for _, line := range strings.Split(out, "\n") {
		line = strings.TrimSpace(line)
		if strings.HasPrefix(line, "FILE:") {
			if cur.name != "" {
				raws = append(raws, cur)
			}
			// name 统一不含 .pub 后缀（与 Delete/Deploy 接口的 name 语义一致）
			base := path.Base(strings.TrimPrefix(line, "FILE:"))
			cur = rawKey{name: strings.TrimSuffix(base, ".pub")}
			continue
		}
		if cur.name == "" {
			continue
		}
		// ssh-keygen -lf: 3072 SHA256:xxxx comment (RSA)
		fields := strings.Fields(line)
		if len(fields) < 3 || !strings.HasPrefix(fields[1], "SHA256:") {
			if line != "" && cur.pub == "" && (strings.HasPrefix(line, "ssh-") || strings.HasPrefix(line, "ecdsa-") || strings.HasPrefix(line, "sk-")) {
				cur.pub = line
			}
			continue
		}
		cur.fpLine = line
		raws = append(raws, cur)
		cur = rawKey{}
	}
	if cur.name != "" {
		raws = append(raws, cur)
	}

	// 全节点 authorized_keys 指纹集合（用于分发状态标记）。
	fps := s.deployedFingerprints(ctx)

	keys := []SshPubKey{}
	for _, r := range raws {
		k := parseKeygenLine(r.name, r.fpLine)
		k.PublicKey = r.pub
		for _, st := range fps {
			_, has := st.fps[k.Fingerprint]
			k.DeployedOn = append(k.DeployedOn, KeyDeployStatus{NodeID: st.nodeID, NodeName: st.nodeName, Deployed: has, Reachable: st.reachable})
		}
		keys = append(keys, k)
	}
	return keys, nil
}

// parseKeygenLine 解析 ssh-keygen -lf 输出行：3072 SHA256:xxxx comment (RSA)。
func parseKeygenLine(name, line string) SshPubKey {
	k := SshPubKey{Name: name}
	fields := strings.Fields(line)
	if len(fields) < 3 {
		return k
	}
	k.Fingerprint = fields[1]
	rest := strings.Join(fields[2:], " ")
	if strings.HasSuffix(rest, ")") {
		if i := strings.LastIndex(rest, "("); i >= 0 {
			k.Type = strings.Trim(rest[i:], "()")
			k.Comment = strings.TrimSpace(rest[:i])
		}
	} else {
		k.Comment = rest
	}
	return k
}

type nodeFP struct {
	nodeID, nodeName string
	fps              map[string]bool // 该节点 authorized_keys 中的指纹集合
	reachable        bool
}

// deployedFingerprints 并发收集全部节点 root authorized_keys 的指纹集合（离线节点 reachable=false）。
func (s *SshGuardService) deployedFingerprints(ctx context.Context) []nodeFP {
	type nodeRef struct{ id, name string }
	refs := []nodeRef{{id: "local", name: s.nodes.Local().Name}}
	for _, n := range s.nodes.ListNodes() {
		if n["remote"] == true {
			id, _ := n["id"].(string)
			name, _ := n["name"].(string)
			if id != "" {
				refs = append(refs, nodeRef{id: id, name: name})
			}
		}
	}
	out := make([]nodeFP, len(refs))
	var wg sync.WaitGroup
	for i, r := range refs {
		wg.Add(1)
		go func(i int, r nodeRef) {
			defer wg.Done()
			cctx, cancel := context.WithTimeout(ctx, 6*time.Second)
			defer cancel()
			out[i] = nodeFP{nodeID: r.id, nodeName: r.name, fps: map[string]bool{}}
			cmd := `if [ -f /root/.ssh/authorized_keys ]; then ssh-keygen -lf /root/.ssh/authorized_keys 2>/dev/null | awk '{print $2}'; fi`
			txt, err := s.exec(cctx, r.id, cmd, 5)
			if err != nil {
				return // 不可达：reachable=false
			}
			out[i].reachable = true
			for _, line := range strings.Split(txt, "\n") {
				if fp := strings.TrimSpace(line); fp != "" {
					out[i].fps[fp] = true
				}
			}
		}(i, r)
	}
	wg.Wait()
	return out
}

var sshKeyNamePattern = regexp.MustCompile(`^[A-Za-z0-9][A-Za-z0-9._-]{0,63}$`)

func validateKeyName(name string) error {
	if !sshKeyNamePattern.MatchString(name) || strings.Contains(name, "..") {
		return errs.Wrap(errs.ErrBadRequest, "密钥名称仅允许字母数字._-，且以字母数字开头")
	}
	return nil
}

// GenerateKey 在节点上生成密钥对（无口令）；私钥留在节点 /root/.ssh/，不回传。
func (s *SshGuardService) GenerateKey(ctx context.Context, nodeID, keyType, name, comment string) (*SshPubKey, error) {
	keyType = strings.ToLower(strings.TrimSpace(keyType))
	if keyType == "" {
		keyType = "ed25519"
	}
	if keyType != "ed25519" && keyType != "rsa" {
		return nil, errs.Wrap(errs.ErrBadRequest, "密钥类型仅支持 ed25519 / rsa")
	}
	if name == "" {
		name = fmt.Sprintf("id_%s_%s", keyType, time.Now().Format("20060102150405"))
	}
	if err := validateKeyName(name); err != nil {
		return nil, err
	}
	if len(comment) > 128 {
		return nil, errs.Wrap(errs.ErrBadRequest, "注释过长")
	}
	bits := ""
	if keyType == "rsa" {
		bits = "-b 4096"
	}
	script := fmt.Sprintf(`set -e
umask 077
mkdir -p /root/.ssh && chmod 700 /root/.ssh
if [ -e "/root/.ssh/$YP_NAME" ] || [ -e "/root/.ssh/$YP_NAME.pub" ]; then echo KEY_EXISTS; exit 2; fi
ssh-keygen -t %s %s -f "/root/.ssh/$YP_NAME" -N '' -C "$YP_COMMENT" >/dev/null 2>&1
echo KEY_GEN_OK
ssh-keygen -lf "/root/.ssh/$YP_NAME.pub" 2>/dev/null
cat "/root/.ssh/$YP_NAME.pub"`, keyType, bits)
	out, code, err := s.execResp(ctx, nodeID, script, map[string]string{"YP_NAME": name, "YP_COMMENT": comment}, 30)
	if err != nil {
		return nil, err
	}
	if code == 2 || strings.Contains(out, "KEY_EXISTS") {
		return nil, errs.Wrap(errs.ErrBadRequest, "同名密钥已存在")
	}
	if code != 0 || !strings.Contains(out, "KEY_GEN_OK") {
		return nil, errs.Wrapc(errs.CodeFileOpFailed, "生成密钥失败: "+firstLine(tail(out, 200)))
	}
	k, pub := parseGenerateOutput(name, out)
	if pub != "" {
		k.PublicKey = pub
	}
	return &k, nil
}

// parseGenerateOutput 从 GenerateKey 脚本输出解析指纹行与公钥文本。
func parseGenerateOutput(name, out string) (SshPubKey, string) {
	pub := ""
	k := SshPubKey{Name: name}
	for _, line := range strings.Split(out, "\n") {
		line = strings.TrimSpace(line)
		// ssh-keygen -lf 行首是 bits（256/3072/...），第二字段才是 SHA256: 指纹
		if fields := strings.Fields(line); len(fields) >= 3 && strings.HasPrefix(fields[1], "SHA256:") {
			k = parseKeygenLine(name, line)
			continue
		}
		if strings.HasPrefix(line, "ssh-") || strings.HasPrefix(line, "ecdsa-") || strings.HasPrefix(line, "sk-") {
			pub = line
		}
	}
	return k, pub
}

// ImportKey 导入公钥（校验格式后存为 /root/.ssh/<name>.pub）。
func (s *SshGuardService) ImportKey(ctx context.Context, nodeID, name, publicKey string) (*SshPubKey, error) {
	publicKey = strings.TrimSpace(publicKey)
	if publicKey == "" || strings.ContainsAny(publicKey, "\n\r") {
		return nil, errs.Wrap(errs.ErrBadRequest, "公钥需为单行文本")
	}
	if name == "" {
		name = fmt.Sprintf("imported_%s", time.Now().Format("20060102150405"))
	}
	if err := validateKeyName(name); err != nil {
		return nil, err
	}
	script := `set -e
umask 077
mkdir -p /root/.ssh && chmod 700 /root/.ssh
if [ -e "/root/.ssh/$YP_NAME.pub" ]; then echo KEY_EXISTS; rm -f /tmp/yp-key-check; exit 2; fi
printf '%s\n' "$YP_PUBKEY" > /tmp/yp-key-check
if ! ssh-keygen -lf /tmp/yp-key-check >/dev/null 2>&1; then echo KEY_INVALID; rm -f /tmp/yp-key-check; exit 3; fi
mv /tmp/yp-key-check "/root/.ssh/$YP_NAME.pub"
echo KEY_IMPORT_OK
ssh-keygen -lf "/root/.ssh/$YP_NAME.pub" 2>/dev/null`
	out, code, err := s.execResp(ctx, nodeID, script, map[string]string{"YP_NAME": name, "YP_PUBKEY": publicKey}, 30)
	if err != nil {
		return nil, err
	}
	switch {
	case code == 2 || strings.Contains(out, "KEY_EXISTS"):
		return nil, errs.Wrap(errs.ErrBadRequest, "同名公钥已存在")
	case code == 3 || strings.Contains(out, "KEY_INVALID"):
		return nil, errs.Wrap(errs.ErrBadRequest, "公钥格式不合法（ssh-keygen 校验未通过）")
	case code != 0:
		return nil, errs.Wrapc(errs.CodeFileOpFailed, "导入失败: "+firstLine(tail(out, 200)))
	}
	k := SshPubKey{Name: name, PublicKey: publicKey}
	for _, line := range strings.Split(out, "\n") {
		line = strings.TrimSpace(line)
		if fields := strings.Fields(line); len(fields) >= 3 && strings.HasPrefix(fields[1], "SHA256:") {
			k = parseKeygenLine(name, line)
			k.PublicKey = publicKey
		}
	}
	return &k, nil
}

// DeleteKey 删除公钥；withPrivate 时连同名私钥一起删。
func (s *SshGuardService) DeleteKey(ctx context.Context, nodeID, name string, withPrivate bool) error {
	if err := validateKeyName(name); err != nil {
		return err
	}
	script := `if [ ! -f "/root/.ssh/` + name + `.pub" ]; then echo KEY_NOT_FOUND; exit 2; fi
rm -f "/root/.ssh/` + name + `.pub"`
	if withPrivate {
		script += "\nrm -f \"/root/.ssh/" + name + "\""
	}
	out, code, err := s.execResp(ctx, nodeID, script, nil, 15)
	if err != nil {
		return err
	}
	if code == 2 || strings.Contains(out, "KEY_NOT_FOUND") {
		return errs.Wrap(errs.ErrBadRequest, "公钥不存在")
	}
	return nil
}

// DeployKey 把源节点上的公钥分发到目标节点 root 的 authorized_keys（指纹去重，幂等）。
func (s *SshGuardService) DeployKey(ctx context.Context, keyNodeID, name, targetNodeID string) (string, error) {
	if err := validateKeyName(name); err != nil {
		return "", err
	}
	if _, err := s.nodes.ByID(targetNodeID); err != nil {
		return "", err
	}
	pub, err := s.exec(ctx, keyNodeID, fmt.Sprintf(`if [ -f /root/.ssh/%s.pub ]; then cat /root/.ssh/%s.pub; else echo KEY_NOT_FOUND; fi`, name, name), 15)
	if err != nil {
		return "", err
	}
	pub = strings.TrimSpace(pub)
	if pub == "" || strings.Contains(pub, "KEY_NOT_FOUND") {
		return "", errs.Wrap(errs.ErrBadRequest, "源节点上不存在该公钥")
	}
	script := `set -e
mkdir -p /root/.ssh && chmod 700 /root/.ssh
touch /root/.ssh/authorized_keys && chmod 600 /root/.ssh/authorized_keys
fp=$(printf '%s\n' "$YP_PUBKEY" | ssh-keygen -lf - 2>/dev/null | awk '{print $2}')
if [ -n "$fp" ] && ssh-keygen -lf /root/.ssh/authorized_keys 2>/dev/null | grep -qF "$fp"; then echo DEPLOY_EXISTS; exit 0; fi
printf '%s\n' "$YP_PUBKEY" >> /root/.ssh/authorized_keys
echo DEPLOY_OK`
	out, code, err := s.execResp(ctx, targetNodeID, script, map[string]string{"YP_PUBKEY": pub}, 30)
	if err != nil {
		return "", err
	}
	if code != 0 {
		return "", errs.Wrapc(errs.CodeFileOpFailed, "分发失败: "+firstLine(tail(out, 200)))
	}
	if strings.Contains(out, "DEPLOY_EXISTS") {
		return "exists", nil
	}
	return "deployed", nil
}

// UndeployKey 从目标节点 root 的 authorized_keys 中移除源节点的公钥（按公钥行精确匹配，幂等）。
func (s *SshGuardService) UndeployKey(ctx context.Context, keyNodeID, name, targetNodeID string) (string, error) {
	if err := validateKeyName(name); err != nil {
		return "", err
	}
	if _, err := s.nodes.ByID(targetNodeID); err != nil {
		return "", err
	}
	pub, err := s.exec(ctx, keyNodeID, fmt.Sprintf(`if [ -f /root/.ssh/%s.pub ]; then cat /root/.ssh/%s.pub; else echo KEY_NOT_FOUND; fi`, name, name), 15)
	if err != nil {
		return "", err
	}
	pub = strings.TrimSpace(pub)
	if pub == "" || strings.Contains(pub, "KEY_NOT_FOUND") {
		return "", errs.Wrap(errs.ErrBadRequest, "源节点上不存在该公钥")
	}
	script := `set -e
f=/root/.ssh/authorized_keys
[ -f "$f" ] || { echo REVOKE_ABSENT; exit 0; }
grep -vF "$YP_PUBKEY" "$f" > "$f.yp-tmp" || true
if cmp -s "$f" "$f.yp-tmp"; then rm -f "$f.yp-tmp"; echo REVOKE_ABSENT; exit 0; fi
mv "$f.yp-tmp" "$f"
chmod 600 "$f"
echo REVOKE_OK`
	out, code, err := s.execResp(ctx, targetNodeID, script, map[string]string{"YP_PUBKEY": pub}, 30)
	if err != nil {
		return "", err
	}
	if code != 0 {
		return "", errs.Wrapc(errs.CodeFileOpFailed, "撤下失败: "+firstLine(tail(out, 200)))
	}
	if strings.Contains(out, "REVOKE_ABSENT") {
		return "absent", nil
	}
	return "revoked", nil
}

// FailedAttemptsMarked SSH 登录失败 IP 聚合，并按 fail2ban（local）标记封禁状态。
func (s *SshGuardService) FailedAttemptsMarked(ctx context.Context, nodeID string, f2b *Fail2banService, limit int) ([]SshAttemptEntry, error) {
	entries, err := s.FailedAttempts(ctx, nodeID, limit)
	if err != nil {
		return nil, err
	}
	// 封禁标记仅对本机数据源有意义（fail2ban 纳管当前为 local）
	if f2b != nil && (nodeID == "" || nodeID == "local") {
		if banned, n := f2b.jailBanned(ctx, "sshd"); n > 0 {
			banSet := map[string]bool{}
			for _, ip := range banned {
				banSet[ip] = true
			}
			for i := range entries {
				entries[i].Banned = banSet[entries[i].IP]
			}
		}
	}
	return entries, nil
}
